spring.application.name=LoanApprovalSystem

# MongoDB configuration
spring.data.mongodb.uri=mongodb://localhost:27017/loanapproval

# Thymeleaf configuration
spring.thymeleaf.prefix=classpath:/templates/

spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
